description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.2.0
      with:
        version: 8.15.9
    - uses: actions/setup-node@v6.2.0
      with:
        node-version: '20.20.0'
        cache: pnpm
    - run: pnpm install --frozen-lockfile
      shell: bash
  using: composite